# Generated by Django 5.2.17 on 2026-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.CharField(max_length=100)),
                ('deporte', models.CharField(choices=[('Fútbol', 'Fútbol'), ('Básquetbol', 'Básquetbol'), ('Vóley', 'Vóley'), ('Pádel', 'Pádel')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_horas', models.FloatField(default=1.0)),
                ('precio_hora', models.FloatField(default=20.0)),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
            ],
        ),
    ]
