# Generated by Django 5.2.17 on 2026-09-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
